name: publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        fetch-depth: 0 # Get all tags - necessary for Gradle versioning
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
          cache: 'gradle'
      - name: Build & Publish
        run: ./gradlew publish --no-daemon
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PKG_PUBLISHING_AUTH_TOKEN }}
